PUT http://localhost:8080/students/10
Accept: application/json
Content-Type: application/json
Authorization: Basic admin:admin123

{
    "firstName": "TEst",
    "lastName": "testy",
    "email": "test@luv2code.com"
}